### ISSUE TITLE
XM bugs

### ISSUE THREAD

**Issue by bryc** [steffest/BassoonTracker#8] opened 2018-12-16 04:19 UTC
This thing transforms whats supposed to sound like [greensleeves](https://github.com/steffest/BassoonTracker/files/2683263/mrgamer-whata.fuks.its.name.zip) into a new beast altogether... Also [a synthetic device](https://github.com/steffest/BassoonTracker/files/2683266/reed-a.synthetic.device.zip) turns into a drum machine/Philip Glass piece.

**Comment by steffest** [comment] 2018-12-16 07:38
Hey! 
Check with http://www.stef.be/bassoontracker/dev.html please, that's the current codebase, not with http://www.stef.be/bassoontracker/ which is an old deployed version :-)
Newest version will be released soon.

**Comment by bryc** [comment] 2018-12-16 07:51
Ah much better! Sorry didn't realize there was a dev page. "a synthetic device" doesn't play properly though. The hi-hat envelope doesn't work I think.

**Comment by steffest** [comment] 2018-12-17 01:39
That's an interesting one - "a synthetic device"!
I didn't even know negative numbers in the volume effect tracks are supported, I have never seen that used before.
I'll re-open the ticket and fix it later this week.
Thanks for testing! I love this little quirky things.

**Comment by bryc** [comment] 2018-12-19 11:51
Here's a bunch of bug reports that may need squishing. Trying to ignore the files that have "unimplemented" console logs you already know about (such as missing vibrato, panning etc).

**Some songs have a bug where a lowpass filter is enabled and remains even after loading new songs (gets "stuck"):**

1. [vogue-ambient light.zip](https://github.com/steffest/BassoonTracker/files/2694234/vogue-ambient.light.zip) (Pattern 9)
2. [lesnik-hot dogs 3.xm](http://artscene.textfiles.com/music/mods/XM/MODLAND/Lesnik/hot%20dogs%203.xm)
3. [lamb-happiness.xm](http://artscene.textfiles.com/music/mods/XM/MODLAND/Lamb/happiness.xm)

That requires refreshing the page to fix, so pretty bad.


**A bunch of songs have issues with ADSR release, similar to springmellow p.II.xm above (seems to be the same issue in all).**

1. [sinny-sky sunday.xm](http://modland.com/pub/modules/Fasttracker%202/Sinny/sky%20sunday.xm)
2. [amove-lupo.xm](https://modarchive.org/index.php?request=view_by_moduleid&query=152718)
3. [ghidorah-dark december.xm](http://artscene.textfiles.com/music/mods/XM/MODLAND/Ghidorah/dark%20december.xm)
4. [xerxes-hesse's sovesang.xm](https://modarchive.org/index.php?request=view_by_moduleid&query=62901)
5.  [jeroen tel-stranglehold.xm](http://artscene.textfiles.com/music/mods/XM/MODLAND/Jeroen%20Tel/stranglehold.xm)

**Next, some have issues with arpeggios:**

1. [maniac-disco zax.xm](http://artscene.textfiles.com/music/mods/XM/MODLAND/Maniac/disco%20zax.xm)
2. [carter-dead feelings.xm](http://artscene.textfiles.com/music/mods/XM/MODLAND/Carter/dead%20feelings.xm)
3. [med-halloween 2002.xm](http://modland.com/pub/modules/Fasttracker%202/Med/halloween%202002.xm) (seems that a 'note-off' technique isn't working here)
4. [lhs-brd keygen #2.mod](https://modarchive.org/index.php?request=view_by_moduleid&query=171951) and [brd keygen #2.xm](http://modland.com/pub/modules/Fasttracker%202/LHS/brd%20keygen%20%232.xm) _both_ don't work properly!

**Some have an issue with fine tune:**

1. [svenzzon-blizzard.zip](https://github.com/steffest/BassoonTracker/files/2694233/svenzzon-blizzard.zip) (Error: `unable to find finetune for note 0`)
2. [strobe-balloons and shit.xm](http://artscene.textfiles.com/music/mods/XM/MODLAND/Strobe/balloons%20and%20shit.xm) (Error: `unable to find finetune for note undefined`)


**Some songs wont play at all due to unimplemented Global Volume Slide:**

1. [reed-yet another discoism.xm](http://modland.com/pub/modules/Fasttracker%202/Reed/yet%20another%20discoism.xm)
2. [cerror-for funky fish.xm](http://modland.com/pub/modules/Fasttracker%202/Cerror/for%20funky%20fish.xm)
3. [radix-sunstreak.xm](http://modland.com/pub/modules/Fasttracker%202/Radix/sunstreak.xm)

**And some others that have miscellaneous problems:** 

1. ghosts 'n goblins.xm (envelope sustain forever)
2. [dubmood-kolobki vodka dance.xm](http://artscene.textfiles.com/music/mods/XM/MODLAND/Dubmood/kolobki%20vodka%20dance.xm) (wrong pattern jump in Pattern 2)
3. [kenet-chip or not.xm](http://artscene.textfiles.com/music/mods/XM/MODLAND/Kenet/chip%20or%20not.xm) (delay/feedback effect not working as it should)
4. [dragoon-far rising sun.xm](http://amp.dascene.net/downmod.php?index=20585) (pad samples not playing)
5. [mystic cloud-for old times sake.zip](https://github.com/steffest/BassoonTracker/files/2694126/mystic.cloud-for.old.times.sake.zip) (**Crashes** on pattern 3)
6. [dubmood - cybernostra weekends.zip](https://github.com/steffest/BassoonTracker/files/2694071/dubmood.-.cybernostra.weekends.zip) (**Crashes** on open - this is a weird custom file but opens fine in FT2/milky)

**Comment by steffest** [comment] 2018-12-19 13:00
Thanks a MILLION!
Really: I know how time-consuming it is to hunt down these examples.

I have split them up in separate issues (#9 to #14) - So I can close one from time to time :-) 
I'll dive in it during the Xmas holidays.

**Comment by steffest** [comment] 2019-01-25 12:10
I think all issues have been fixed.
Adding Autovibrato in the past weeks caused some regressions but I think we're good now.

**Closed by steffest** 2019-01-25 12:10 UTC

**Comment by bryc** [comment] 2019-01-25 17:47
awesome work <3 xm support is very solid now!

**Comment by eteeselink** [comment] 2019-01-30 18:39
First of _wow_ this is spectacularly awesome!! Extremely well done. I'm impressed across the board, but especially about the amazing mobile support. I couldn't have imagined that an oldschool style tracker UI could be user friendly (ish) on a tiny touch screen. Hats off!

That said, I don't think all the XM bugs have been fixed yet; I found an old (pretty bad) song of mine that's pretty different in Bassoon Tracker vs FT2 or XMPlay, especially in the first few patterns. Something with the pitch bend and also something with the timing I think. 

https://www.stef.be/bassoontracker/?file=https%3A%2F%2Fapi.modarchive.org%2Fdownloads.php%3Fmoduleid%3D142113

https://modarchive.org/index.php?request=view_by_moduleid&query=142113

**Comment by steffest** [comment] 2019-01-30 20:38
@eteeselink Yes indeed! The "M" command should also continue the previous "3" command slide value. that's a bug. I created a new ticket.

**Comment by metaphysician** [comment] 2019-02-10 19:01
Hey there! noticed a nice thread here for XM-related playback bugs. i have a XM file that plays back pretty close to the original except that the panning doesn't work. i'm not a tracker expert but i opened this up in the FastTracker2 clone for macOS and it plays fine in that one. it seems the panning is added to the instrument/sample and not the Track? 

anyway in Bassoon the file seems to be recognized as a mono only file and no panning seems to be working, although panning data does show on the sample editor (Bassoon and FT2 show it as happening on samples labeled '1','2' and '3'.).

here's the link to the XM (i resaved this in the FastTracker II clone):
https://www.dropbox.com/s/cjklawkg42go68w/dots1.xm?dl=0

and here's the MP3 of the song for comparison. the panning is pretty important, due to the ambient quality of the music:
https://www.dropbox.com/s/qumv11abxgjad5t/dots.mp3?dl=0

anyway - hope this helps a bit!

**Comment by steffest** [comment] 2019-02-10 19:56
@metaphysician 
I bet you're using Safari? 
Somewhere deep down in the "Readme/Missing features and bugs" is this:
"Safari doesn't support WebAudio StereoPanners so songs will be played in mono on Safari."

There's a [shim](https://github.com/mohayonao/stereo-panner-shim) that fixes this but it is too slow.
Safari does support 3D panners though, so I could/should just implement that, haven't gotten around to it.

If you use Chrome or Firefox you will get stereo/panning.

**Comment by metaphysician** [comment] 2019-02-10 20:20
> @metaphysician
> I bet you're using Safari?
> Somewhere deep down in the "Readme/Missing features and bugs" is this:
> "Safari doesn't support WebAudio StereoPanners so songs will be played in mono on Safari."
> 
> There's a [shim](https://github.com/mohayonao/stereo-panner-shim) that fixes this but it is too slow.
> Safari does support 3D panners though, so I could/should just implement that, haven't gotten around to it.
> 
> If you use Chrome or Firefox you will get stereo/panning.

thanks! i was wondering if it wasn't possibly a browser issue. should have checked that before and avoided bothering you. apologies - it works great in Firefox!
