### ISSUE TITLE
Sample editor indexing is decimal, tracker view uses hex

### ISSUE THREAD

**Issue by BleuLlama** [steffest/BassoonTracker#42] opened 2019-02-16 15:52 UTC
The sample numbers in the tracker view are in hex (00..0F,10..1F,etc) but the sample editor selector displays in decimal.  (00..09,10..19,etc).

The sample editor should probably be in hex as well.  It makes finding the right sample a bit tricky. ;)

**Comment by steffest** [comment] 2019-02-17 14:54
I'm still wondering about the correct approach with these hex/dec things ...
I'll probably throw it in a setting so the user can choose, maybe even give an option to go decimal all the way, including the pattern view.

**Comment by steffest** [comment] 2019-04-17 06:22
Closing this as it's a duplicate of #23

**Closed by steffest** 2019-04-17 06:22 UTC
Labels: enhancement
