### ISSUE TITLE
Tracker crashed on Firefox 63 on Linux Debian 9 with Gnome

### ISSUE THREAD

**Issue by Jean-MarcS** [steffest/BassoonTracker#17] opened 2019-01-30 15:31 UTC
Hello.

I tried your fantastic memory bringer tracker and it freezed and get stucked in a sound loop.

I was playing Stardust Memories, and it happened on the 63th step.

I copy you what lies in my syslog around when it happened (might not be all relevant, nor connected to the problem, but if it can helps !)

```Jan 30 15:11:57 debianjm firefox[16482]: Theme parsing error: <data>:1:34: Expected ')' in color definition
Jan 30 15:11:57 debianjm firefox[16482]: Theme parsing error: <data>:1:77: Expected ')' in color definition
Jan 30 15:13:36 debianjm org.gnome.Shell.desktop[3485]: libinput error: client bug: timer event0 debounce short: offset negative (-9ms)
Jan 30 15:13:46 debianjm gnome-shell[3485]: Object St.BoxLayout (0x55f3d5518890), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Jan 30 15:13:46 debianjm gnome-shell[3485]: Object St.BoxLayout (0x55f3d54ec810), has been already deallocated — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Jan 30 15:13:46 debianjm org.gnome.Shell.desktop[3485]: == Stack trace for context 0x55f3d36991d0 ==
Jan 30 15:13:46 debianjm org.gnome.Shell.desktop[3485]: #0   55f3ded2b618 i   resource:///org/gnome/shell/ui/status/volume.js:101 (7fe7638091f0 @ 49)
Jan 30 15:13:46 debianjm org.gnome.Shell.desktop[3485]: #1   7ffe954afcf0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fe79c0b0b80 @ 71)
Jan 30 15:13:46 debianjm org.gnome.Shell.desktop[3485]: #2   55f3ded2b568 i   resource:///org/gnome/shell/ui/status/volume.js:284 (7fe763809c10 @ 259)
Jan 30 15:13:46 debianjm org.gnome.Shell.desktop[3485]: #3   7ffe954b0c60 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fe79c0b0b80 @ 71)
Jan 30 15:13:46 debianjm org.gnome.Shell.desktop[3485]: #4   55f3ded2b4e0 i   /home/jeanmarc/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/widget/volume.js:422 (7fe762745af0 @ 91)
Jan 30 15:13:46 debianjm org.gnome.Shell.desktop[3485]: #5   7ffe954b1fb0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fe79c0b0b80 @ 71)
Jan 30 15:13:46 debianjm org.gnome.Shell.desktop[3485]: #6   55f3ded2b420 i   self-hosted:979 (7fe79c0f01f0 @ 440)
Jan 30 15:13:46 debianjm org.gnome.Shell.desktop[3485]: == Stack trace for context 0x55f3d36991d0 ==
Jan 30 15:13:46 debianjm org.gnome.Shell.desktop[3485]: #0   55f3ded2b618 i   resource:///org/gnome/shell/ui/status/volume.js:101 (7fe7638091f0 @ 49)
Jan 30 15:13:46 debianjm org.gnome.Shell.desktop[3485]: #1   7ffe954afcf0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fe79c0b0b80 @ 71)
Jan 30 15:13:46 debianjm org.gnome.Shell.desktop[3485]: #2   55f3ded2b568 i   resource:///org/gnome/shell/ui/status/volume.js:284 (7fe763809c10 @ 259)
Jan 30 15:13:46 debianjm org.gnome.Shell.desktop[3485]: #3   7ffe954b0c60 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fe79c0b0b80 @ 71)
Jan 30 15:13:46 debianjm org.gnome.Shell.desktop[3485]: #4   55f3ded2b4e0 i   /home/jeanmarc/.local/share/gnome-shell/extensions/shell-volume-mixer@derhofbauer.at/widget/volume.js:422 (7fe762745af0 @ 91)
Jan 30 15:13:46 debianjm org.gnome.Shell.desktop[3485]: #5   7ffe954b1fb0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (7fe79c0b0b80 @ 71)
Jan 30 15:13:46 debianjm org.gnome.Shell.desktop[3485]: #6   55f3ded2b420 i   self-hosted:979 (7fe79c0f01f0 @ 440)
```

Nice work !

JM

**Comment by steffest** [comment] 2019-01-30 20:44
Hey!
2 questions:

1. Could you retry that on https://www.stef.be/bassoontracker/dev.html?file=demomods%2FStardustMemories.mod ?
That's a dev version where the console log is enabled.
Does it say anything in the browser console when it happens?
2. Do you by any chance have one of those fancy 120 mhz screens?

Thanks!

**Comment by Jean-MarcS** [comment] 2019-01-31 16:01
Hi.

So I opened the console.

Here what I have when I load the page : 

```ticktime: 0.02 tracker.js:59:2
UI assets loaded main.js:52:4
Assets init done assets.js:329:3
Setting SkipFrame to 1 main.js:513:3
Format ID: M.K. detect.js:29:3
set BPM: 125 to 125 tracker.js:1641:3
Reading sample from 0x21564 with length of 10320 bytes and repeat length of 2 protracker.js:123:5
Reading sample from 0x31884 with length of 7168 bytes and repeat length of 2 protracker.js:123:5
Reading sample from 0x39052 with length of 2416 bytes and repeat length of 2 protracker.js:123:5
Reading sample from 0x41468 with length of 1616 bytes and repeat length of 2 protracker.js:123:5
Reading sample from 0x43084 with length of 3614 bytes and repeat length of 844 protracker.js:123:5
Reading sample from 0x46698 with length of 7904 bytes and repeat length of 4580 protracker.js:123:5
Reading sample from 0x54602 with length of 2192 bytes and repeat length of 2 protracker.js:123:5
Reading sample from 0x56794 with length of 9936 bytes and repeat length of 5718 protracker.js:123:5
Reading sample from 0x66730 with length of 9968 bytes and repeat length of 5696 protracker.js:123:5
Reading sample from 0x76698 with length of 2158 bytes and repeat length of 1704 protracker.js:123:5
Reading sample from 0x78856 with length of 43522 bytes and repeat length of 37328 protracker.js:123:5
Reading sample from 0x122378 with length of 1104 bytes and repeat length of 2 protracker.js:123:5
Reading sample from 0x123482 with length of 10640 bytes and repeat length of 2 protracker.js:123:5
Reading sample from 0x134122 with length of 7762 bytes and repeat length of 5226 protracker.js:123:5
Reading sample from 0x141884 with length of 2304 bytes and repeat length of 2 protracker.js:123:5
Reading sample from 0x144188 with length of 9488 bytes and repeat length of 126 protracker.js:123:5
Reading sample from 0x153676 with length of 0 bytes and repeat length of 2 protracker.js:123:5 (x15)
no font for char 94 bitmapfont.js:155:20 (x8)```

(Last ones 15 times and 8 times)

I've tried twice. First one, my browser was opened from yesterday (when it crashed after the bug :smile: ). I had deezer opened in another tab, and it was on pause. The second time, I started fresh.


When I started the song the second time (fresh browser) : 

```Audio context is suspended - trying to resume audio.js:137:17```

And then at the exact moment when it crashed : 

```applying instrument offset cache to instrument 11 tracker.js:527:6```

Additionally, I've pasted my whole syslog here : https://pastebin.com/p8HLz770
It's on the page load, and I'm not sure it's relevant at all.

I unfortunately don't own a fancy screen, but I've got two regular ones (which can be indeed relevant). I tried with Firefox on both, had the same result.

Last thing, it's on the step 60 that it crashes.

JM

**Comment by steffest** [comment] 2019-02-01 15:13
Thanks. That's a completely normal console log output.
I'll try to reproduce it.

**Comment by steffest** [comment] 2020-04-14 07:35
Closing this - can't reproduce it.

**Closed by steffest** 2020-04-14 07:35 UTC
Labels: to be investigated
